### ISSUE TITLE
Install Slack instead of Hipchat

### ISSUE THREAD

**Issue by YSavir** [ga-instructors/installfest_script#48]
We're moving over to Slack! January is already using it instead of Hipchat.

Is it just a matter of updating `scripts/mac/install_apps.sh`? I see Hipchat is also mentioned in a few other files (`tests/old_tests` and `scripts/set_default_gems_with_rbenv`). Do they (or any other files) also need to be updated?

**Comment by h4w5** [comment]
Done.
